### ISSUE TITLE
request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 3 passed to Contao\Model::findBy() must be of the type array, null given"

### ISSUE THREAD

**Issue by DenFin** [heart-bits/hb-contacts-bundle#1]
Hi there,

this extension was exactly what I was looking for. But after creating a new contact this error showed up in the backend and frontend. It seems to me that this is a bug. Any chance that it might get fixed? I would really like to continue using this extension.

`request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 3 passed to Contao\Model::findBy() must be of the type array, null given, called in /html/contao-neu/vendor/heart-bits/contao-contacts-bundle/src/Resources/contao/elements/Contact.php on line 78" at /html/contao-neu/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php line 925 {"exception":"[object] (TypeError(code: 0): Argument 3 passed to Contao\\Model::findBy() must be of the type array, null given, called in /html/contao-neu/vendor/heart-bits/contao-contacts-bundle/src/Resources/contao/elements/Contact.php on line 78 at /html/contao-neu/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:925)"} []`

**Comment by saschawustmann** [comment]
Fixed in 1.3.4.
Thanks for your feedback, @DenFin!
