### ISSUE TITLE
Fehler bei Bildgröße

### ISSUE THREAD

**Issue by exscorp** [heart-bits/hb-contacts-bundle#3]
Hallo Sascha, wenn man beim Inhaltselement eine der folgenden Bildgrößen (siehe screenshot) des Ansprechpartners einstellt bekommt man im Frontend dann ein Fehler. Contao Version 4.11.4.

![Screenshot 2021-06-14 171622](https://user-images.githubusercontent.com/3008649/121916449-6fa4d900-cd34-11eb-8fd1-666a8b305202.jpg)

Fehler:
`request.CRITICAL: Uncaught PHP Exception Contao\Image\Exception\InvalidArgumentException: "Mode must be one of the Contao\Image\ResizeConfiguration::MODE_* constants" at C:\laragon\www\domain\vendor\contao\image\src\ResizeConfiguration.php line 97 {"exception":"[object] (Contao\\Image\\Exception\\InvalidArgumentException(code: 0): Mode must be one of the Contao\\Image\\ResizeConfiguration::MODE_* constants at C:\\laragon\\www\\domain\\vendor\\contao\\image\\src\\ResizeConfiguration.php:97)"} []`

**Comment by saschawustmann** [comment]
Fixed in 1.3.5
